import type { Console } from "./index.js";

/**
 * The canonical catalog of consoles roomba knows about — sourced from Batocera.
 * `alias` is the Batocera ROM-folder name (the placement target under
 * /userdata/roms/<alias>). `name` and `category` come from the Batocera systems
 * wiki (https://wiki.batocera.org/systems); folders with no wiki entry fall back
 * to name = alias, category = "port". Engines map their internal ids onto these
 * aliases; `roomba consoles` only shows the ones an installed engine maps.
 */
export const CONSOLES: readonly Console[] = [
  // --- Arcade ---
  { name: "Multiple Arcade Machine Emulator (MAME)", alias: "mame", category: "arcade" },
  { name: "FinalBurn Neo", alias: "fbneo", category: "arcade" },
  { name: "Discrete Integrated Circuit Emulator (DICE)", alias: "dice", category: "arcade" },
  { name: "DAPHNE (Laserdisc)", alias: "daphne", category: "arcade" },
  { name: "Singe (Laserdisc)", alias: "singe", category: "arcade" },
  { name: "Namco System 22", alias: "namco22", category: "arcade" },
  { name: "Sega Model 2", alias: "model2", category: "arcade" },
  { name: "Sega Model 3", alias: "model3", category: "arcade" },
  { name: "Sega NAOMI", alias: "naomi", category: "arcade" },
  { name: "Sega NAOMI 2", alias: "naomi2", category: "arcade" },
  { name: "Namco System 246/256", alias: "namco2x6", category: "arcade" },
  { name: "Sega Hikaru", alias: "hikaru", category: "arcade" },
  { name: "Gaelco 3D", alias: "gaelco", category: "arcade" },
  { name: "Sega Chihiro", alias: "chihiro", category: "arcade" },
  { name: "Triforce", alias: "triforce", category: "arcade" },
  { name: "Sammy Atomiswave", alias: "atomiswave", category: "arcade" },
  { name: "Cave CV1000", alias: "cave3rd", category: "arcade" },
  { name: "Sega System SP", alias: "systemsp", category: "arcade" },
  { name: "Sega Lindbergh", alias: "lindbergh", category: "arcade" },

  // --- Home console ---
  { name: "Fairchild Channel F", alias: "channelf", category: "home-console" },
  { name: "Atari 2600", alias: "atari2600", category: "home-console" },
  { name: "Magnavox Odyssey²", alias: "odyssey2", category: "home-console" },
  { name: "Bally Astrocade", alias: "astrocade", category: "home-console" },
  { name: "APF-MP1000", alias: "apfm1000", category: "home-console" },
  { name: "Interton VC 4000", alias: "vc4000", category: "home-console" },
  { name: "Intellivision", alias: "intellivision", category: "home-console" },
  { name: "Bandai Super Vision 8000", alias: "sv8000", category: "home-console" },
  { name: "Epoch Cassette Vision", alias: "cassettevision", category: "home-console" },
  { name: "Atari 5200", alias: "atari5200", category: "home-console" },
  { name: "ColecoVision", alias: "colecovision", category: "home-console" },
  { name: "Entex Adventure Vision", alias: "advision", category: "home-console" },
  { name: "Vectrex", alias: "vectrex", category: "home-console" },
  { name: "VTech CreatiVision", alias: "crvision", category: "home-console" },
  { name: "Emerson Arcadia 2001", alias: "arcadia", category: "home-console" },
  { name: "Nintendo Entertainment System", alias: "nes", category: "home-console" },
  { name: "Sega SG-1000", alias: "sg1000", category: "home-console" },
  { name: "Othello Multivision", alias: "multivision", category: "home-console" },
  { name: "Philips Videopac+ G7400", alias: "videopacplus", category: "home-console" },
  { name: "Casio PV-1000", alias: "pv1000", category: "home-console" },
  { name: "Casio PV-2000", alias: "pv2000", category: "home-console" },
  { name: "Gakken Compact Vision TV Boy", alias: "ctvboy", category: "home-console" },
  { name: "Epoch Super Cassette Vision", alias: "scv", category: "home-console" },
  { name: "Sega Master System", alias: "mastersystem", category: "home-console" },
  { name: "Famicom Disk System", alias: "fds", category: "home-console" },
  { name: "Atari 7800", alias: "atari7800", category: "home-console" },
  { name: "VTech Socrates", alias: "socrates", category: "home-console" },
  { name: "PC Engine / TurboGrafx-16", alias: "pcengine", category: "home-console" },
  { name: "Sega Genesis / Mega Drive", alias: "megadrive", category: "home-console" },
  { name: "PC Engine CD-ROM² / TurboGrafx-CD", alias: "pcenginecd", category: "home-console" },
  { name: "PC Engine SuperGrafx", alias: "supergrafx", category: "home-console" },
  { name: "Super Nintendo Entertainment System", alias: "snes", category: "home-console" },
  { name: "Neo Geo", alias: "neogeo", category: "home-console" },
  { name: "Philips CD-i", alias: "cdi", category: "home-console" },
  { name: "Commodore CDTV", alias: "amigacdtv", category: "home-console" },
  { name: "Amstrad GX4000", alias: "gx4000", category: "home-console" },
  { name: "Sega CD / Mega-CD", alias: "megacd", category: "home-console" },
  { name: "SNES MSU-1", alias: "snes-msu1", category: "home-console" },
  { name: "Sega Pico", alias: "pico", category: "home-console" },
  { name: "Super Game Boy", alias: "sgb", category: "home-console" },
  { name: "Super A'Can", alias: "supracan", category: "home-console" },
  { name: "Mega Drive MSU-MD", alias: "megadrive-msu", category: "home-console" },
  { name: "Super Game Boy MSU-1", alias: "sgb-msu1", category: "home-console" },
  { name: "Atari Jaguar", alias: "jaguar", category: "home-console" },
  { name: "3DO Interactive Multiplayer", alias: "3do", category: "home-console" },
  { name: "Amiga CD32", alias: "amigacd32", category: "home-console" },
  { name: "Sega 32X", alias: "sega32x", category: "home-console" },
  { name: "Sony PlayStation", alias: "psx", category: "home-console" },
  { name: "NEC PC-FX", alias: "pcfx", category: "home-console" },
  { name: "Neo Geo CD", alias: "neogeocd", category: "home-console" },
  { name: "Sega Saturn", alias: "saturn", category: "home-console" },
  { name: "Casio Loopy", alias: "loopy", category: "home-console" },
  { name: "Virtual Boy", alias: "virtualboy", category: "home-console" },
  { name: "Satellaview", alias: "satellaview", category: "home-console" },
  { name: "Atari Jaguar CD", alias: "jaguarcd", category: "home-console" },
  { name: "SuFami Turbo", alias: "sufami", category: "home-console" },
  { name: "Nintendo 64", alias: "n64", category: "home-console" },
  { name: "Sega Dreamcast", alias: "dreamcast", category: "home-console" },
  { name: "Nintendo 64DD", alias: "n64dd", category: "home-console" },
  { name: "Sony PlayStation 2", alias: "ps2", category: "home-console" },
  { name: "Nintendo GameCube", alias: "gamecube", category: "home-console" },
  { name: "Microsoft Xbox", alias: "xbox", category: "home-console" },
  { name: "Plug & Play TV Games", alias: "tvgames", category: "home-console" },
  { name: "Sega Advanced Pico Beena", alias: "beena", category: "home-console" },
  { name: "VTech V.Smile", alias: "vsmile", category: "home-console" },
  { name: "Microsoft Xbox 360", alias: "xbox360", category: "home-console" },
  { name: "Nintendo Wii", alias: "wii", category: "home-console" },
  { name: "Sony PlayStation 3", alias: "ps3", category: "home-console" },
  { name: "Nintendo Wii U", alias: "wiiu", category: "home-console" },
  { name: "Sony PlayStation 4", alias: "ps4", category: "home-console" },
  { name: "Uzebox", alias: "uzebox", category: "home-console" },
  { name: "PICO-8", alias: "pico8", category: "home-console" },
  { name: "TIC-80", alias: "tic80", category: "home-console" },
  { name: "LowRes NX", alias: "lowresnx", category: "home-console" },
  { name: "WASM-4", alias: "wasm4", category: "home-console" },
  { name: "Pyxel", alias: "pyxel", category: "home-console" },
  { name: "Vircon32", alias: "vircon32", category: "home-console" },

  // --- Portable ---
  { name: "Nintendo Game & Watch", alias: "gameandwatch", category: "portable" },
  { name: "Handheld LCD Games", alias: "lcdgames", category: "portable" },
  { name: "Epoch Game Pocket Computer", alias: "gamepock", category: "portable" },
  { name: "Game Boy", alias: "gb", category: "portable" },
  { name: "Game Boy (2 Players)", alias: "gb2players", category: "portable" },
  { name: "Atari Lynx", alias: "lynx", category: "portable" },
  { name: "Sega Game Gear", alias: "gamegear", category: "portable" },
  { name: "Bit Corporation Gamate", alias: "gamate", category: "portable" },
  { name: "Hartung Game Master", alias: "gmaster", category: "portable" },
  { name: "Watara Supervision", alias: "supervision", category: "portable" },
  { name: "Mega Duck / Cougar Boy", alias: "megaduck", category: "portable" },
  { name: "Tiger Game.com", alias: "gamecom", category: "portable" },
  { name: "Game Boy Color", alias: "gbc", category: "portable" },
  { name: "Game Boy Color (2 Players)", alias: "gbc2players", category: "portable" },
  { name: "Neo Geo Pocket", alias: "ngp", category: "portable" },
  { name: "Neo Geo Pocket Color", alias: "ngpc", category: "portable" },
  { name: "Bandai WonderSwan", alias: "wswan", category: "portable" },
  { name: "Bandai WonderSwan Color", alias: "wswanc", category: "portable" },
  { name: "Game Boy Advance", alias: "gba", category: "portable" },
  { name: "Nintendo Pokémon Mini", alias: "pokemini", category: "portable" },
  { name: "GamePark GP32", alias: "gp32", category: "portable" },
  { name: "Nintendo DS", alias: "nds", category: "portable" },
  { name: "PlayStation Portable", alias: "psp", category: "portable" },
  { name: "Nintendo 3DS", alias: "3ds", category: "portable" },
  { name: "PlayStation Vita", alias: "psvita", category: "portable" },
  { name: "Arduboy", alias: "arduboy", category: "portable" },

  // --- Home computer ---
  { name: "DEC PDP-1", alias: "pdp1", category: "home-computer" },
  { name: "Apple II", alias: "apple2", category: "home-computer" },
  { name: "Commodore PET", alias: "pet", category: "home-computer" },
  { name: "TRS-80", alias: "trs80", category: "home-computer" },
  { name: "Sharp MZ-80K", alias: "mz80k", category: "home-computer" },
  { name: "Atari 800", alias: "atari800", category: "home-computer" },
  { name: "Acorn Atom", alias: "atom", category: "home-computer" },
  { name: "Texas Instruments TI-99/4A", alias: "ti99", category: "home-computer" },
  { name: "NEC PC-8001", alias: "pc80", category: "home-computer" },
  { name: "Commodore VIC-20", alias: "c20", category: "home-computer" },
  { name: "TRS-80 Color Computer", alias: "coco", category: "home-computer" },
  { name: "NEC PC-6000", alias: "pc60", category: "home-computer" },
  { name: "NEC PC-8800", alias: "pc88", category: "home-computer" },
  { name: "Sinclair ZX81", alias: "zx81", category: "home-computer" },
  { name: "BBC Micro", alias: "bbcmicro", category: "home-computer" },
  { name: "Sharp X1", alias: "x1", category: "home-computer" },
  { name: "ZX Spectrum", alias: "zxspectrum", category: "home-computer" },
  { name: "Commodore 64", alias: "c64", category: "home-computer" },
  { name: "NEC PC-9800", alias: "pc98", category: "home-computer" },
  { name: "Fujitsu FM-7", alias: "fm7", category: "home-computer" },
  { name: "Tomy Tutor", alias: "tutor", category: "home-computer" },
  { name: "EACA Colour Genie", alias: "cgenie", category: "home-computer" },
  { name: "Sharp MZ-700", alias: "mz700", category: "home-computer" },
  { name: "Sharp MZ-2000", alias: "mz2000", category: "home-computer" },
  { name: "Acorn Electron", alias: "electron", category: "home-computer" },
  { name: "Camputers Lynx", alias: "camplynx", category: "home-computer" },
  { name: "MSX", alias: "msx1", category: "home-computer" },
  { name: "Coleco Adam", alias: "adam", category: "home-computer" },
  { name: "Spectravideo", alias: "spectravideo", category: "home-computer" },
  { name: "Bandai RX-78", alias: "rx78", category: "home-computer" },
  { name: "Sega SC-3000", alias: "sc3000", category: "home-computer" },
  { name: "TRS-80 MC-10", alias: "mc10", category: "home-computer" },
  { name: "Dragon 64", alias: "dragon64", category: "home-computer" },
  { name: "Amstrad CPC", alias: "amstradcpc", category: "home-computer" },
  { name: "Apple Macintosh", alias: "macintosh", category: "home-computer" },
  { name: "Thomson MO/TO", alias: "thomson", category: "home-computer" },
  { name: "Commodore Plus/4", alias: "cplus4", category: "home-computer" },
  { name: "VTech Laser 310", alias: "laser310", category: "home-computer" },
  { name: "Oric Atmos", alias: "oricatmos", category: "home-computer" },
  { name: "Sharp MZ-800", alias: "mz800", category: "home-computer" },
  { name: "Atari ST", alias: "atarist", category: "home-computer" },
  { name: "MSX2", alias: "msx2", category: "home-computer" },
  { name: "Commodore 128", alias: "c128", category: "home-computer" },
  { name: "Enterprise", alias: "enterprise", category: "home-computer" },
  { name: "Amstrad PCW", alias: "pcw", category: "home-computer" },
  { name: "Elektronika BK", alias: "bk", category: "home-computer" },
  { name: "Sharp MZ-2500", alias: "mz2500", category: "home-computer" },
  { name: "Apple IIGS", alias: "apple2gs", category: "home-computer" },
  { name: "Sega AI Computer", alias: "segaai", category: "home-computer" },
  { name: "Videoton TVC", alias: "tvc", category: "home-computer" },
  { name: "Acorn Archimedes", alias: "archimedes", category: "home-computer" },
  { name: "Atari XEGS", alias: "xegs", category: "home-computer" },
  { name: "Amiga 500", alias: "amiga500", category: "home-computer" },
  { name: "Sharp X68000", alias: "x68000", category: "home-computer" },
  { name: "MSX2+", alias: "msx2+", category: "home-computer" },
  { name: "Fujitsu FM Towns", alias: "fmtowns", category: "home-computer" },
  { name: "SAM Coupé", alias: "samcoupe", category: "home-computer" },
  { name: "Amiga 1200", alias: "amiga1200", category: "home-computer" },
  { name: "Tandy VIS", alias: "vis", category: "home-computer" },
  { name: "MSX turboR", alias: "msxturbor", category: "home-computer" },
  { name: "Commander X16", alias: "commanderx16", category: "home-computer" },

  // --- Port, Flatpak & Miscellaneous ---
  { name: "DOS (DOSBox)", alias: "dos", category: "port" },
  { name: "Windows (WINE)", alias: "windows", category: "port" },
  { name: "Windows Installers", alias: "windows_installers", category: "port" },
  { name: "Flatpak", alias: "flatpak", category: "port" },
  { name: "Steam", alias: "steam", category: "port" },
  { name: "Ports", alias: "ports", category: "port" },
  { name: "Flash (Flashpoint)", alias: "flash", category: "port" },
  { name: "Moonlight", alias: "moonlight", category: "port" },
  { name: "VGM Play", alias: "vgmplay", category: "port" },
  { name: "Abuse", alias: "abuse", category: "port" },
  { name: "BennuGD", alias: "bennugd", category: "port" },
  { name: "Blake Stone", alias: "bstone", category: "port" },
  { name: "Cannonball (OutRun)", alias: "cannonball", category: "port" },
  { name: "CatacombGL", alias: "catacomb", category: "port" },
  { name: "Cave Story (NXEngine)", alias: "cavestory", category: "port" },
  { name: "C-Dogs SDL", alias: "cdogs", category: "port" },
  { name: "Commander Genius", alias: "cgenius", category: "port" },
  { name: "CorsixTH (Theme Hospital)", alias: "corsixth", category: "port" },
  { name: "DevilutionX (Diablo)", alias: "devilutionx", category: "port" },
  { name: "Doom 3 BFG", alias: "doom3", category: "port" },
  { name: "DXX-Rebirth (Descent)", alias: "dxx-rebirth", category: "port" },
  { name: "EasyRPG", alias: "easyrpg", category: "port" },
  { name: "ECWolf", alias: "ecwolf", category: "port" },
  { name: "EDuke32 (Duke Nukem 3D)", alias: "eduke32", category: "port" },
  { name: "ET: Legacy", alias: "etlegacy", category: "port" },
  { name: "Fallout CE", alias: "fallout1-ce", category: "port" },
  { name: "Fallout 2 CE", alias: "fallout2-ce", category: "port" },
  { name: "Ion Fury", alias: "fury", category: "port" },
  { name: "GZDoom", alias: "gzdoom", category: "port" },
  { name: "Half-Life (Xash3D)", alias: "halflife", category: "port" },
  { name: "Hydra Castle Labyrinth", alias: "hcl", category: "port" },
  { name: "Hurrican", alias: "hurrican", category: "port" },
  { name: "Ikemen GO", alias: "ikemen", category: "port" },
  { name: "Return to Castle Wolfenstein (ioRTCW)", alias: "iortcw", category: "port" },
  { name: "Jazz Jackrabbit 2", alias: "jazz2", category: "port" },
  { name: "Jedi Knight: Dark Forces II (OpenJKDF2)", alias: "jkdf2", category: "port" },
  { name: "Star Wars: Jedi Academy (OpenJK)", alias: "jknight", category: "port" },
  { name: "Lutro", alias: "lutro", category: "port" },
  { name: "Medal of Honor: Allied Assault", alias: "mohaa", category: "port" },
  { name: "Mr. Boom", alias: "mrboom", category: "port" },
  { name: "M.U.G.E.N", alias: "mugen", category: "port" },
  { name: "OpenBOR", alias: "openbor", category: "port" },
  { name: "OpenJazz", alias: "openjazz", category: "port" },
  { name: "PrBoom", alias: "prboom", category: "port" },
  { name: "Pygame", alias: "pygame", category: "port" },
  { name: "Quake", alias: "quake", category: "port" },
  { name: "Quake II", alias: "quake2", category: "port" },
  { name: "Quake III Arena", alias: "quake3", category: "port" },
  { name: "Raze", alias: "raze", category: "port" },
  { name: "REminiscence (Flashback)", alias: "reminiscence", category: "port" },
  { name: "Rise of the Triad", alias: "rott", category: "port" },
  { name: "Return to Castle Wolfenstein", alias: "rtcw", category: "port" },
  { name: "ScummVM", alias: "scummvm", category: "port" },
  { name: "SDLPoP (Prince of Persia)", alias: "sdlpop", category: "port" },
  { name: "Solarus", alias: "solarus", category: "port" },
  { name: "Sonic Mania", alias: "sonic-mania", category: "port" },
  { name: "Sonic 3 A.I.R.", alias: "sonic3-air", category: "port" },
  { name: "Sonic Retro (Sonic 1/2/CD)", alias: "sonicretro", category: "port" },
  { name: "Super Mario War", alias: "superbroswar", category: "port" },
  { name: "The Force Engine", alias: "theforceengine", category: "port" },
  { name: "TheXTech (Super Mario Bros. X)", alias: "thextech", category: "port" },
  { name: "Tomb Raider (TR1X)", alias: "traider1", category: "port" },
  { name: "Tomb Raider II (TR2X)", alias: "traider2", category: "port" },
  { name: "OpenTyrian", alias: "tyrian", category: "port" },
  { name: "Visual Pinball X", alias: "vpinball", category: "port" },
  { name: "XRick (Rick Dangerous)", alias: "xrick", category: "port" },
  { name: "Zelda Classic", alias: "zc210", category: "port" },
];

/** Look up a canonical console by its Batocera alias/folder name. */
export const CONSOLE_BY_ALIAS: ReadonlyMap<string, Console> = new Map(
  CONSOLES.map((console) => [console.alias, console]),
);
