/**
 * Accepted ROM-file extensions per Batocera system alias, sourced from each
 * system's `_info.txt` "ROM files extensions accepted" line. Lowercase, no
 * leading dot. THE authority for whether a downloaded file is runnable as-is
 * (and therefore whether a downloaded archive must be extracted first).
 */
export const SYSTEM_EXTENSIONS: Readonly<Record<string, readonly string[]>> = {
  // Arcade
  mame: ["zip", "7z"],
  fbneo: ["zip", "7z"],
  dice: ["zip", "dmy"],
  daphne: ["daphne", "squashfs"],
  singe: ["daphne", "squashfs"],
  namco22: ["zip", "7z"],
  namco2x6: ["zip"],
  model2: ["zip"],
  model3: ["zip"],
  naomi: ["lst", "bin", "dat", "zip", "7z"],
  naomi2: ["zip", "7z"],
  hikaru: ["zip", "7z"],
  gaelco: ["zip", "7z"],
  chihiro: ["iso"],
  triforce: ["iso", "rvz"],
  atomiswave: ["lst", "bin", "dat", "zip", "7z"],
  cave3rd: ["zip", "7z"],
  systemsp: ["lst", "bin", "dat", "zip", "7z"],
  lindbergh: ["game"],

  // Home consoles
  channelf: ["zip", "rom", "bin", "chf"],
  atari2600: ["a26", "bin", "zip", "7z"],
  odyssey2: ["bin", "zip", "7z"],
  astrocade: ["bin", "zip", "7z"],
  apfm1000: ["bin", "zip", "7z"],
  vc4000: ["bin", "rom", "pgm", "tvc", "zip", "7z"],
  intellivision: ["int", "bin", "rom", "zip", "7z"],
  sv8000: ["bin", "zip", "7z"],
  cassettevision: ["zip", "bin777"],
  atari5200: ["rom", "xfd", "atr", "atx", "cdm", "cas", "car", "bin", "a52", "xex", "zip", "7z"],
  colecovision: ["bin", "col", "rom", "zip", "7z"],
  advision: ["bin", "zip", "7z"],
  vectrex: ["bin", "gam", "vec", "zip", "7z"],
  crvision: ["bin", "rom", "zip", "7z"],
  arcadia: ["bin", "zip", "7z"],
  nes: ["nes", "unif", "unf", "zip", "7z"],
  sg1000: ["bin", "sg", "zip", "7z"],
  multivision: ["bin", "sg", "zip", "7z"],
  videopacplus: ["bin", "zip", "7z"],
  pv1000: ["bin", "zip", "7z"],
  pv2000: ["bin", "cas", "zip", "7z"],
  ctvboy: ["bin", "zip", "7z"],
  scv: ["bin", "zip", "0"],
  mastersystem: ["bin", "sms", "zip", "7z"],
  fds: ["fds", "zip", "7z"],
  atari7800: ["a78", "bin", "zip", "7z"],
  socrates: ["bin", "zip", "7z"],
  pcengine: ["pce", "bin", "zip", "7z"],
  megadrive: ["bin", "gen", "md", "sg", "smd", "zip", "7z"],
  pcenginecd: ["pce", "cue", "ccd", "iso", "img", "chd"],
  supergrafx: ["pce", "sgx", "cue", "ccd", "chd", "zip", "7z"],
  snes: ["smc", "fig", "sfc", "gd3", "gd7", "dx2", "bsx", "swc", "zip", "7z"],
  neogeo: ["7z", "zip"],
  cdi: ["chd", "cue", "toc", "nrg", "gdi", "iso", "cdr"],
  amigacdtv: ["bin", "cue", "iso", "chd", "m3u"],
  gx4000: ["dsk", "m3u", "cpr", "zip", "7z"],
  megacd: ["cue", "iso", "chd", "m3u"],
  "snes-msu1": ["smc", "sfc", "squashfs"],
  pico: ["bin", "md", "zip", "7z"],
  sgb: ["gb", "gbc", "zip", "7z"],
  supracan: ["bin", "zip", "7z"],
  "megadrive-msu": ["md", "zip", "7z", "squashfs"],
  "sgb-msu1": ["gb", "gbc", "zip", "7z", "squashfs"],
  jaguar: ["j64", "jag", "cof", "abs", "rom", "zip", "7z"],
  "3do": ["iso", "chd", "cue"],
  amigacd32: ["bin", "cue", "iso", "chd"],
  sega32x: ["32x", "chd", "smd", "bin", "md", "zip", "7z"],
  saturn: ["cue", "ccd", "m3u", "chd", "iso", "zip", "mds"],
  vis: ["chd", "cue", "toc", "nrg", "gdi", "iso", "cdr"],
  beena: ["bin", "zip", "7z"],
  gamate: ["bin", "zip", "7z"],
  gmaster: ["bin", "zip", "7z"],
  gamepock: ["bin", "zip", "7z"],
  supervision: ["sv", "zip", "7z"],
  megaduck: ["bin", "zip", "7z"],
  rx78: ["bin", "zip", "7z"],
  loopy: ["bin", "ic1", "zip", "7z"],
  vsmile: ["u1", "u3", "bin", "zip", "7z"],
  segaai: ["bin", "wav", "flac", "cas", "zip", "7z"],

  // Disc & modern consoles
  psx: ["cue", "img", "mdf", "pbp", "toc", "cbn", "m3u", "ccd", "chd", "iso"],
  ps2: ["iso", "mdf", "nrg", "bin", "img", "dump", "gz", "cso", "chd", "m3u"],
  ps3: ["ps3", "psn", "iso", "squashfs"],
  ps4: ["ps4"],
  psp: ["iso", "cso", "pbp", "chd"],
  psvita: ["zip", "psvita"],
  dreamcast: ["cdi", "cue", "gdi", "chd", "m3u"],
  neogeocd: ["cue", "iso", "chd"],
  pcfx: ["cue", "ccd", "toc", "chd", "zip", "7z", "m3u"],
  jaguarcd: ["cue", "cdi", "bigpimg"],
  n64: ["z64", "n64", "v64", "zip", "7z"],
  n64dd: ["z64", "n64", "ndd", "zip", "7z"],
  nds: ["nds", "bin", "zip", "7z"],
  "3ds": ["3ds", "cci", "cxi", "cia", "axf", "elf", "app", "squashfs", "zcci", "zcia", "zcxi"],
  gamecube: ["gcm", "iso", "gcz", "ciso", "wbfs", "rvz", "elf", "dol", "m3u", "json"],
  wii: ["gcm", "iso", "gcz", "ciso", "wbfs", "wad", "rvz", "elf", "dol", "m3u", "json"],
  wiiu: ["wua", "wup", "wud", "wux", "rpx", "squashfs", "wuhb"],
  xbox: ["iso", "squashfs"],
  xbox360: ["iso", "xex", "xbox360", "zar"],

  // Handhelds
  gb: ["gb", "zip", "7z"],
  gbc: ["gbc", "zip", "7z"],
  gba: ["gba", "zip", "7z"],
  gb2players: ["gb", "gb2", "gbc2", "zip", "7z"],
  gbc2players: ["gbc", "gb2", "gbc2", "zip", "7z"],
  gamegear: ["bin", "gg", "zip", "7z"],
  gamecom: ["bin", "tgc", "zip", "7z"],
  lynx: ["bll", "lnx", "lyx", "o", "zip", "7z"],
  ngp: ["ngp", "zip", "7z"],
  ngpc: ["ngc", "zip", "7z"],
  wswan: ["ws", "zip", "7z"],
  wswanc: ["wsc", "zip", "7z"],
  virtualboy: ["vb", "zip", "7z"],
  pokemini: ["min", "zip", "7z"],
  gp32: ["smc", "zip", "7z"],
  gameandwatch: ["mgw", "zip", "7z"],
  lcdgames: ["mgw", "zip", "7z"],

  // Home computers
  amiga500: ["adf", "uae", "ipf", "dms", "dmz", "adz", "lha", "hdf", "exe", "m3u", "zip", "raw", "scp"],
  amiga1200: ["adf", "uae", "ipf", "dms", "dmz", "adz", "lha", "hdf", "exe", "m3u", "zip", "raw", "scp"],
  amstradcpc: ["dsk", "sna", "tap", "cdt", "voc", "m3u", "zip", "7z"],
  apple2: ["nib", "do", "po", "dsk", "mfi", "dfi", "rti", "edd", "woz", "wav", "zip", "7z", "chd", "hdv", "2mg"],
  apple2gs: ["2mg", "do", "nib", "po", "dsk"],
  atari800: ["rom", "xfd", "atr", "atx", "cdm", "cas", "car", "bin", "a52", "xex", "zip", "7z", "m3u"],
  atarist: ["st", "msa", "stx", "dim", "ipf", "m3u", "zip", "7z", "hd", "gemdos"],
  xegs: ["atr", "dsk", "xfd", "bin", "rom", "car", "zip", "7z"],
  bbcmicro: ["mfi", "dfi", "hfe", "mfm", "td0", "imd", "d77", "d88", "1dd", "cqm", "cqi", "dsk", "ima", "img", "ufi", "360", "ipf", "ssd", "bbc", "dsd", "adf", "ads", "adm", "adl", "fsd", "wav", "tap", "bin", "zip", "7z"],
  electron: ["wav", "csw", "uef", "mfi", "dfi", "hfe", "mfm", "td0", "imd", "d77", "d88", "1dd", "cqm", "cqi", "dsk", "ssd", "bbc", "img", "dsd", "adf", "ads", "adm", "adl", "rom", "bin", "zip", "7z"],
  atom: ["wav", "tap", "csw", "uef", "mfi", "dfi", "hfe", "mfm", "td0", "imd", "d77", "d88", "1dd", "cqm", "cqi", "dsk", "40t", "atm", "bin", "rom", "zip", "7z"],
  archimedes: ["mfi", "dfi", "hfe", "mfm", "td0", "imd", "d77", "d88", "1dd", "cqm", "cqi", "dsk", "ima", "img", "ufi", "360", "ipf", "adf", "apd", "jfd", "ads", "adm", "adl", "ssd", "bbc", "dsd", "st", "msa", "chd", "zip", "7z"],
  c64: ["d64", "d71", "d81", "crt", "prg", "tap", "t64", "m3u", "zip", "7z", "nib", "g64"],
  c128: ["d64", "d81", "prg", "lnx", "m3u", "zip", "7z"],
  c20: ["20", "40", "60", "rom", "a0", "b0", "crt", "d64", "d81", "prg", "tap", "t64", "m3u", "zip", "7z"],
  cplus4: ["d64", "prg", "tap", "m3u", "zip", "7z"],
  pet: ["a0", "b0", "crt", "d64", "d81", "prg", "tap", "t64", "m3u", "zip", "7z"],
  commanderx16: ["bas", "img", "prg"],
  dragon64: ["wav", "cas", "dsk", "dmk", "ccc", "rom", "bin", "zip", "7z"],
  coco: ["wav", "cas", "dsk", "ccc", "rom", "zip", "7z"],
  camplynx: ["wav", "tap", "ldf", "zip", "7z"],
  cgenie: ["cas", "wav", "zip", "7z"],
  enterprise: ["bas", "com", "zip", "img", "dsk", "tap", "dtf", "trn", "128", "cas", "cdt", "tzx"],
  laser310: ["vz", "wav", "cas", "zip", "7z"],
  mc10: ["wav", "cas", "rom", "bin", "zip", "7z"],
  samcoupe: ["cpm", "dsk", "sad", "mgt", "sdf", "td0", "sbt", "zip"],
  spectravideo: ["zip", "7z", "cas"],
  trs80: ["cmd", "cas", "dsk", "dmk", "bas", "wav", "zip", "7z"],
  adam: ["wav", "ddp", "mfi", "dfi", "hfe", "mfm", "td0", "imd", "d77", "d88", "1dd", "cqm", "cqi", "dsk", "rom", "col", "bin", "zip", "7z"],
  tutor: ["bin", "wav", "zip", "7z"],
  ti99: ["rpk", "wav", "zip", "7z"],
  pcw: ["mfi", "dfi", "mfm", "td0", "imd", "86f", "d77", "d88", "1dd", "cqm", "cqi", "dsk", "zip", "7z"],
  bk: ["bin", "img", "dsk", "bkd", "zip", "7z"],
  msx1: ["dsk", "mx1", "rom", "zip", "7z", "cas", "m3u", "ogv", "openmsx"],
  msx2: ["dsk", "mx2", "rom", "zip", "7z", "cas", "m3u", "ogv", "openmsx"],
  "msx2+": ["dsk", "mx2", "rom", "zip", "7z", "cas", "m3u", "openmsx"],
  msxturbor: ["dsk", "mx2", "rom", "zip", "7z", "openmsx", "m3u"],
  zxspectrum: ["tzx", "tap", "z80", "rzx", "scl", "trd", "dsk", "zip", "7z"],
  zx81: ["tzx", "p", "zip", "7z"],
  oricatmos: ["tap", "dsk", "zip"],
  thomson: ["fd", "sap", "k7", "m7", "m5", "rom", "zip"],
  tvc: ["cas", "tap", "dsk", "img", "zip"],
  fm7: ["wav", "t77", "mfi", "dfi", "hfe", "mfm", "td0", "imd", "d77", "d88", "1dd", "cqm", "cqi", "dsk", "zip", "7z"],
  fmtowns: ["bin", "m3u", "cue", "d88", "d77", "xdf", "iso", "chd", "toc", "nrg", "gdi", "cdr", "mfi", "dfi", "hfe", "mfm", "td0", "imd", "1dd", "cqm", "cqi", "dsk", "zip", "7z"],
  pc60: ["bin", "cas", "p6", "d77", "d88", "dsk", "1dd", "mfi", "dfi", "mfm", "td0", "imd", "cqm", "cqi", "xdf", "hdm", "2hd", "fdi", "zip", "7z"],
  pc80: ["d77", "d88", "1dd", "dsk", "n80", "bin", "zip", "7z"],
  pc88: ["cmt", "d88", "u88", "m3u"],
  pc98: ["d98", "zip", "98d", "fdi", "fdd", "2hd", "tfd", "d88", "88d", "hdm", "xdf", "dup", "cmd", "hdi", "thd", "nhd", "hdd", "hdn", "m3u"],
  x1: ["dx1", "zip", "2d", "2hd", "tfd", "d88", "88d", "hdm", "xdf", "dup", "cmd", "7z"],
  x68000: ["dim", "img", "d88", "88d", "hdm", "dup", "2hd", "xdf", "hdf", "cmd", "m3u", "zip", "7z"],
  mz80k: ["mzf", "mzt", "m12", "wav", "zip", "7z"],
  mz700: ["mzf", "mzt", "m12", "wav", "zip", "7z"],
  mz800: ["mzf", "mzt", "m12", "wav", "zip", "7z"],
  mz2000: ["mzf", "mzt", "m12", "wav", "d88", "dsk", "zip", "7z"],
  mz2500: ["d88", "dsk", "mfi", "dfi", "hfe", "mfm", "td0", "imd", "d77", "1dd", "cqm", "cqi", "zip", "7z"],
  macintosh: ["dsk", "zip", "7z", "mfi", "dfi", "hfe", "mfm", "td0", "imd", "d77", "d88", "1dd", "cqm", "cqi", "ima", "img", "ufi", "ipf", "dc42", "woz", "2mg", "360", "chd", "cue", "toc", "nrg", "gdi", "iso", "cdr", "hd", "hdv", "hdi"],
  pdp1: ["zip", "7z", "tap", "rim", "drm"],

  // Fantasy / engine consoles & other cartridge systems
  arduboy: ["hex", "zip", "7z"],
  uzebox: ["uze", "bin", "zip"],
  vircon32: ["v32", "zip"],
  wasm4: ["wasm"],
  lowresnx: ["nx", "zip", "7z"],
  pico8: ["p8", "png", "m3u"],
  tic80: ["tic"],
  pyxel: ["py", "pyxapp"],
  pygame: ["pygame"],
  lutro: ["lutro", "zip", "7z"],
  vgmplay: ["vgm", "vgz", "zip", "7z"],
  sufami: ["st", "fig", "bs", "smc", "sfc", "zip", "7z"],
  satellaview: ["bs", "smc", "sfc", "zip", "7z", "squashfs"],
  sc3000: ["bin", "sg", "wav", "cas", "bit", "zip", "7z"],
  flash: ["swf"],
  tvgames: ["zip", "7z"],
  openbor: ["pak"],
  solarus: ["zip", "solarus"],
  sonicretro: ["son", "scd"],
  ikemen: ["ikemen", "pc"],
  mugen: ["pc"],
  bennugd: ["dcb", "dat"],

  // Ports & standalone engines
  abuse: ["game"],
  catacomb: ["game"],
  cdogs: ["game"],
  corsixth: ["game"],
  halflife: ["game"],
  hcl: ["game"],
  hurrican: ["game"],
  jazz2: ["game"],
  openjazz: ["game"],
  superbroswar: ["game"],
  tyrian: ["game"],
  bstone: ["bstone"],
  cannonball: ["cannonball"],
  cavestory: ["exe"],
  cgenius: ["cgenius"],
  devilutionx: ["mpq"],
  doom3: ["d3"],
  "dxx-rebirth": ["d1x", "d2x"],
  ecwolf: ["ecwolf", "pk3", "squashfs"],
  eduke32: ["eduke32"],
  etlegacy: ["etl"],
  "fallout1-ce": ["f1ce"],
  "fallout2-ce": ["f2ce"],
  fury: ["grp"],
  gzdoom: ["wad", "iwad", "pwad", "gzdoom"],
  jknight: ["jedi"],
  jkdf2: ["jedi"],
  mohaa: ["mohaa"],
  moonlight: ["moonlight"],
  mrboom: ["libretro"],
  prboom: ["wad", "iwad", "pwad"],
  quake: ["quake"],
  quake2: ["quake2", "zip", "7zip"],
  quake3: ["quake3"],
  raze: ["raze"],
  reminiscence: ["rem"],
  rott: ["rott"],
  rtcw: ["rtcw"],
  scummvm: ["scummvm", "squashfs"],
  sdlpop: ["sdlpop"],
  "sonic-mania": ["sman"],
  "sonic3-air": ["s3air"],
  theforceengine: ["tfe"],
  thextech: ["smbx", "squashfs"],
  traider1: ["croft"],
  traider2: ["croft"],
  zc210: ["qst"],
  vpinball: ["vpx"],
  easyrpg: ["easyrpg", "squashfs", "zip"],
  dos: ["pc", "dos", "zip", "squashfs", "dosz", "m3u", "iso", "cue"],
  windows: ["pc", "exe", "wine", "wsquashfs", "wtgz"],
  windows_installers: ["exe", "iso", "msi"],
  steam: ["steam"],
  flatpak: ["flatpak"],
  ports: ["sh", "squashfs"],
  xrick: ["zip"],
};

/** Accepted extensions for an alias (empty array if the alias has no entry). */
export function acceptedExtensions(alias: string): readonly string[] {
  return SYSTEM_EXTENSIONS[alias] ?? [];
}

/** Archive formats roomba can extract (lowercase, no dot). */
export const EXTRACTABLE = ["zip", "7z", "rar"] as const;

/** What to do with a file just placed in an alias's ROM folder. */
export type PostDownloadPlan =
  | { kind: "keep" } // extension accepted, or no data for the alias → leave it
  | { kind: "extract"; archive: string } // not accepted but extractable → unpack
  | { kind: "manual"; ext: string }; // not accepted and not extractable → warn

/** Lowercased extension after the last dot, or "" if there is none. */
function fileExt(filename: string): string {
  const dot = filename.lastIndexOf(".");
  return dot < 0 ? "" : filename.slice(dot + 1).toLowerCase();
}

/**
 * Decide what to do with a file just placed in `alias`'s ROM folder. Pure — no
 * I/O. Callers apply it only for Batocera ROM placement. An alias with no
 * catalog entry, or a file whose extension the system already accepts, yields
 * `keep`, so missing data never risks corrupting a romset.
 */
export function planPostDownload(alias: string, filename: string): PostDownloadPlan {
  const accepted = acceptedExtensions(alias);
  const ext = fileExt(filename);
  if (accepted.length === 0) return { kind: "keep" };
  if (ext === "" || accepted.includes(ext)) return { kind: "keep" };
  if ((EXTRACTABLE as readonly string[]).includes(ext)) {
    return { kind: "extract", archive: filename };
  }
  return { kind: "manual", ext };
}
